Draft PR - rework user auth.
ordercloud-api/ordercloud-dotnet-catalyst pull request #19
Opened 2021-04-08 13:52 UTC by oliverheywood451

- Add oauth/cert method of token verification
- Make VerifiedUserContext injectable via dependency injection instead of a property on the BaseController
- Add a IOrderCloudClient on the VerifiedUserContext so users can make requests in that context easily.

2021-04-12 22:05 UTC, lauerya approved these changes

2021-04-12 22:06 UTC, crhistianramirez requested changes

2021-04-12 22:06 UTC, crhistianramirez commented on library/OrderCloud.Catalyst/Auth/UserAuth/JwtOrderCloud.cs
> +		public DateTime? ExpiresUTC { get; set; }
Why is this nullable if it should always be non-null

2021-04-12 22:06 UTC, crhistianramirez commented on library/OrderCloud.Catalyst/Auth/UserAuth/JwtOrderCloud.cs
> +		public DateTime? NotValidBeforeUTC { get; set; }
Same with this one

2021-04-13 17:17 UTC, crhistianramirez approved these changes

2021-04-13 20:17 UTC, merged